# Generated by Django 5.2.6 on 2026-03-31 20:48

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientes_sistemas', '0008_cliente_observacoes'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MotivoExcecaoSLA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('ativo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Motivo de Exceção SLA',
                'verbose_name_plural': 'Motivos de Exceção SLA',
            },
        ),
        migrations.CreateModel(
            name='MotivoPerda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('ativo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Motivo de Perda',
                'verbose_name_plural': 'Motivos de Perda',
            },
        ),
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nome_contato', models.CharField(max_length=150)),
                ('nome_empresa', models.CharField(max_length=150)),
                ('telefone', models.CharField(max_length=20)),
                ('cidade', models.CharField(max_length=100)),
                ('origem', models.CharField(choices=[('SITE', 'Site'), ('INDICACAO_CONTABIL', 'Indicação Contábil'), ('INDICACAO_CLIENTE', 'Indicação Cliente'), ('GOOGLE', 'Google'), ('WHATSAPP', 'Whatsapp'), ('LIGACAO', 'Ligação'), ('VISITA_CLIENTE', 'Visita do Cliente'), ('VISITA_AO_CLIENTE', 'Visita ao Cliente')], max_length=50)),
                ('etapa', models.CharField(choices=[('1_PROSPECCAO', '1. Lead / Prospecção'), ('2_QUALIFICACAO', '2. Primeiro Contato / Qualificação'), ('3_DIAGNOSTICO', '3. Diagnóstico / Levantamento'), ('4_PROPOSTA', '4. Proposta Enviada / Follow-up'), ('5_NEGOCIACAO', '5. Negociação'), ('6_GANHO', '6. Ganho'), ('7_PERDIDO', '7. Perdido')], default='1_PROSPECCAO', max_length=30)),
                ('dor_principal', models.TextField(blank=True, null=True)),
                ('necessidade_desejo', models.TextField(blank=True, null=True)),
                ('urgencia', models.CharField(choices=[('ALTA', 'Alta'), ('MEDIA', 'Média'), ('BAIXA', 'Baixa')], default='MEDIA', max_length=10)),
                ('valor_equipamentos', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('valor_mensalidade', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('valor_servicos', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('ultima_atualizacao', models.DateTimeField(auto_now=True)),
                ('data_limite_proximo_contato', models.DateTimeField(blank=True, null=True)),
                ('status_sla', models.CharField(choices=[('VERDE', 'Dentro do Prazo'), ('AMARELO', 'Atenção'), ('LARANJA', 'Exceção / Aguardando'), ('VERMELHO', 'Atrasado / Alerta')], default='VERDE', max_length=15)),
                ('justificativa_excecao', models.TextField(blank=True, null=True)),
                ('detalhe_perda', models.TextField(blank=True, null=True)),
                ('data_fechamento', models.DateTimeField(blank=True, null=True)),
                ('cliente_existente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='clientes_sistemas.cliente')),
                ('vendedor_responsavel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='meus_leads', to=settings.AUTH_USER_MODEL)),
                ('motivo_excecao', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='crm_vendas.motivoexcecaosla')),
                ('motivo_perda', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='crm_vendas.motivoperda')),
            ],
            options={
                'verbose_name': 'Lead',
                'verbose_name_plural': 'Leads',
                'ordering': ['-data_criacao'],
            },
        ),
        migrations.CreateModel(
            name='HistoricoMovimentacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_hora', models.DateTimeField(auto_now_add=True)),
                ('acao', models.CharField(max_length=255)),
                ('detalhes', models.TextField(blank=True, null=True)),
                ('vendedor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historico', to='crm_vendas.lead')),
            ],
            options={
                'ordering': ['-data_hora'],
            },
        ),
        migrations.CreateModel(
            name='ArquivoProposta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arquivo', models.FileField(upload_to='crm/propostas/%Y/%m/')),
                ('nome_arquivo', models.CharField(max_length=255)),
                ('data_upload', models.DateTimeField(auto_now_add=True)),
                ('vendedor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='arquivos', to='crm_vendas.lead')),
            ],
        ),
        migrations.CreateModel(
            name='AnotacaoLead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.TextField()),
                ('etapa_no_momento', models.CharField(max_length=30)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('vendedor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='anotacoes', to='crm_vendas.lead')),
            ],
            options={
                'ordering': ['-data_criacao'],
            },
        ),
    ]
