# Generated by Django 5.2.6 on 2026-04-09 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm_vendas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='cnpj',
            field=models.CharField(blank=True, max_length=18, null=True, verbose_name='CNPJ'),
        ),
    ]
