# Generated by Django 5.2.6 on 2026-04-09 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm_vendas', '0003_vendapessoal_metausuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anotacaolead',
            name='etapa_no_momento',
            field=models.CharField(max_length=500),
        ),
    ]
