# Generated by Django 5.2.6 on 2026-04-14 20:11

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm_vendas', '0005_lead_ativo_lead_data_prospeccao_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='data_entrada_etapa',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='lead',
            name='data_limite_sla',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='data_prevista_reciclagem',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='motivo_extensao_sla',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='resgatar_reciclagem',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='lead',
            name='etapa',
            field=models.CharField(choices=[('0_PROSPECCAO', '0. Mesa de Prospecção'), ('1_LEAD', '1. Lead Recebido'), ('2_CONTATO', '2. Primeiro Contato / Qualificação'), ('3_DIAGNOSTICO', '3. Diagnóstico Técnico'), ('4_PROPOSTA', '4. Proposta Enviada'), ('5_NEGOCIACAO', '5. Negociação'), ('6_GANHO', '6. Ganho'), ('7_PERDIDO', '7. Perdido')], default='0_PROSPECCAO', max_length=30),
        ),
        migrations.AlterField(
            model_name='lead',
            name='origem',
            field=models.CharField(choices=[('SITE', 'Site'), ('INDICACAO_CONTABIL', 'Indicação Contábil'), ('INDICACAO_CLIENTE', 'Indicação Cliente'), ('GOOGLE', 'Google'), ('WHATSAPP', 'Whatsapp'), ('LIGACAO', 'Ligação'), ('VISITA_CLIENTE', 'Visita do Cliente'), ('VISITA_AO_CLIENTE', 'Visita ao Cliente'), ('RECICLAGEM', 'Reciclagem')], max_length=50),
        ),
    ]
