# Generated by Django 5.2.6 on 2026-04-21 15:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm_vendas', '0007_segmento_lead_forma_pagamento_lead_prazo_pagamento_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemProposta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('PRODUTO', 'Produto / Equipamento'), ('SERVICO', 'Serviço / Implantação'), ('MENSALIDADE', 'Licença / Mensalidade')], max_length=20)),
                ('nome', models.CharField(max_length=200)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=12)),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens_proposta', to='crm_vendas.lead')),
            ],
            options={
                'ordering': ['tipo', 'nome'],
            },
        ),
    ]
