# Generated by Django 5.2.6 on 2026-05-11 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm_vendas', '0008_itemproposta'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemproposta',
            name='quantidade',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
