# Generated by Django 5.2.6 on 2026-02-13 20:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atendimentos_chamados', '0002_setor_remove_atendimento_cs_gerado_and_more'),
        ('users', '0002_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='setor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='usuarios', to='atendimentos_chamados.setor'),
        ),
    ]
