# Generated by Django X.Y on 2025-10-29
from django.db import migrations, models
import django.db.models.deletion
import arquivos_instaladores.models
from django.conf import settings


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ArquivoItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=180, verbose_name='Título')),
                ('categoria', models.CharField(choices=[('instaladores', 'Instaladores'), ('atualizacoes', 'Atualizações'), ('utilitarios', 'Utilitários'), ('driver-impressao', 'Driver Impressão'), ('balancas', 'Balanças'), ('scripts', 'Scripts'), ('documentos', 'Documentos'), ('certificados', 'Certificados')], db_index=True, max_length=32, verbose_name='Categoria')),
                ('versao', models.CharField(blank=True, max_length=40, verbose_name='Versão')),
                ('descricao', models.TextField(blank=True, verbose_name='Descrição')),
                ('arquivo', models.FileField(blank=True, null=True, upload_to=arquivos_instaladores.models.upload_to_categoria, verbose_name='Arquivo')),
                ('link_externo', models.URLField(blank=True, verbose_name='Link externo (opcional)')),
                ('tamanho_bytes', models.PositiveBigIntegerField(default=0, editable=False, verbose_name='Tamanho (bytes)')),
                ('checksum_sha256', models.CharField(blank=True, editable=False, max_length=64, verbose_name='SHA256')),
                ('is_ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('criado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploads', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Arquivo / Instalador',
                'verbose_name_plural': 'Arquivos e Instaladores',
                'ordering': ('-criado_em',),
            },
        ),
    ]
