# Generated by Django 5.2.6 on 2026-07-18 19:09

import arquivos_instaladores.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arquivos_instaladores', '0002_downloads_indexes '),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='arquivoitem',
            new_name='arquivos_in_categor_108e43_idx',
            old_name='arq_cat_criado_idx',
        ),
        migrations.RenameIndex(
            model_name='arquivoitem',
            new_name='arquivos_in_is_ativ_135b26_idx',
            old_name='arq_ativo_idx',
        ),
        migrations.AlterField(
            model_name='arquivoitem',
            name='arquivo',
            field=models.FileField(blank=True, max_length=255, null=True, upload_to=arquivos_instaladores.models.upload_to_categoria, verbose_name='Arquivo'),
        ),
    ]
