# Generated by Django 5.2.6 on 2026-02-13 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes_sistemas', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cliente',
            options={'ordering': ['razao_social']},
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='complemento',
        ),
        migrations.AddField(
            model_name='cliente',
            name='email_responsavel',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='cliente',
            name='nome_responsavel',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='cliente',
            name='telefone_responsavel',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
