# Generated by Django 5.2.6 on 2026-02-13 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes_sistemas', '0002_alter_cliente_options_remove_cliente_complemento_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='backup_contratado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='cliente',
            name='faturamento_cliente',
            field=models.CharField(choices=[('A', 'A - Alta'), ('B', 'B - Média'), ('C', 'C - Baixa')], default='C', max_length=1),
        ),
        migrations.AddField(
            model_name='cliente',
            name='hospedagem_datacenter',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='cliente',
            name='visibilidade_cliente',
            field=models.CharField(choices=[('A', 'A - Alta'), ('B', 'B - Média'), ('C', 'C - Baixa')], default='C', max_length=1),
        ),
    ]
