# Generated by Django 5.2.6 on 2026-02-13 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes_sistemas', '0003_cliente_backup_contratado_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='faturamento_cliente',
            field=models.CharField(choices=[('A', 'A - Alta'), ('B', 'B - Média'), ('C', 'C - Baixa'), ('D', 'D - Muito Baixa')], default='C', max_length=1),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='visibilidade_cliente',
            field=models.CharField(choices=[('A', 'A - Alta'), ('B', 'B - Média'), ('C', 'C - Baixa'), ('D', 'D - Muito Baixa')], default='C', max_length=1),
        ),
    ]
