# Generated by Django 5.2.6 on 2026-02-20 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes_sistemas', '0004_alter_cliente_faturamento_cliente_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='serial_sistema',
            field=models.CharField(blank=True, help_text='Serial/licença principal do sistema do cliente', max_length=100, null=True),
        ),
    ]
