# Generated by Django 5.2.6 on 2026-02-24 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes_sistemas', '0005_cliente_serial_sistema'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='data_ultimo_calculo',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cliente',
            name='health_score',
            field=models.IntegerField(default=100, verbose_name='Saúde do Cliente'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='nivel_risco',
            field=models.CharField(choices=[('BAIXO', 'Baixo Risco'), ('MEDIO', 'Risco Médio'), ('ALTO', 'Alto Risco'), ('CRITICO', 'Risco Crítico')], default='BAIXO', max_length=20),
        ),
    ]
