# Generated by Django 5.2.6 on 2026-02-24 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes_sistemas', '0006_cliente_data_ultimo_calculo_cliente_health_score_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='status_financeiro',
            field=models.CharField(choices=[('EM_DIA', 'Em Dia'), ('PENDENTE', 'Pendente')], default='EM_DIA', max_length=10, verbose_name='Status Financeiro'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='serial_sistema',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
