# Generated by Django 5.2.6 on 2026-03-23 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes_sistemas', '0007_cliente_status_financeiro_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='observacoes',
            field=models.TextField(blank=True, help_text='Anotações importantes sobre este cliente que aparecerão no chat do bot.', null=True, verbose_name='Observações Internas'),
        ),
    ]
