# Generated by Django 5.2.6 on 2026-04-08 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes_sistemas', '0008_cliente_observacoes'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='regime_tributario',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Regime Tributário'),
        ),
    ]
