# Generated by Django 5.2.6 on 2026-04-08 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes_sistemas', '0009_cliente_regime_tributario'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='data_consulta_cnpj',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Última Consulta de CNPJ'),
        ),
    ]
