# Generated by Django 5.2.6 on 2026-05-29 16:04

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RaioXConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('senha_mestra', models.CharField(default='logica2026', help_text='Senha Mestra para liberar o acesso ao painel de Auditoria.', max_length=255)),
                ('peso_os', models.IntegerField(default=15, help_text='Pontos por cada O.S. concluída no Radar.')),
                ('peso_implantacao', models.IntegerField(default=10, help_text='Pontos de bônus por O.S. de implantação de cliente ou módulo.')),
                ('peso_cs', models.IntegerField(default=8, help_text='Pontos por contato/ação de Customer Success realizada.')),
                ('peso_agenda', models.IntegerField(default=5, help_text='Pontos por agendamentos e visitas externas concluídas.')),
                ('peso_msg_zap', models.DecimalField(decimal_places=2, default=Decimal('0.10'), help_text='Pontos por cada mensagem individual enviada por técnicos no WhatsApp.', max_digits=4)),
            ],
            options={
                'verbose_name': 'Configuração do Raio-X',
                'verbose_name_plural': 'Configurações do Raio-X',
            },
        ),
    ]
