# Generated by Django 5.2.6 on 2026-05-29 17:33

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('raio_x', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='raioxconfig',
            name='peso_avaliacao',
            field=models.IntegerField(default=5, help_text='Pontos por avaliação positiva (4 ou 5 estrelas) recebida do cliente no WhatsApp.'),
        ),
        migrations.AlterField(
            model_name='raioxconfig',
            name='peso_agenda',
            field=models.IntegerField(default=40, help_text='Pontos por agendamentos e visitas externas concluídas.'),
        ),
        migrations.AlterField(
            model_name='raioxconfig',
            name='peso_cs',
            field=models.IntegerField(default=17, help_text='Pontos por contato/ação de Customer Success realizada.'),
        ),
        migrations.AlterField(
            model_name='raioxconfig',
            name='peso_implantacao',
            field=models.IntegerField(default=50, help_text='Pontos de bônus por O.S. de implantação de cliente ou módulo.'),
        ),
        migrations.AlterField(
            model_name='raioxconfig',
            name='peso_msg_zap',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.05'), help_text='Pontos por cada mensagem individual enviada por técnicos no WhatsApp.', max_digits=4),
        ),
        migrations.AlterField(
            model_name='raioxconfig',
            name='peso_os',
            field=models.IntegerField(default=35, help_text='Pontos por cada O.S. concluída no Radar.'),
        ),
        migrations.AlterField(
            model_name='raioxconfig',
            name='senha_mestra',
            field=models.CharField(default='@H3xt0r111', help_text='Senha Mestra para liberar o acesso ao painel de Auditoria.', max_length=255),
        ),
    ]
