# Generated by Django 5.2.6 on 2025-10-30 19:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Credential',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Título')),
                ('username', models.CharField(blank=True, max_length=200, null=True, verbose_name='Usuário / Login')),
                ('encrypted_password', models.BinaryField()),
                ('encrypted_notes', models.BinaryField(blank=True, null=True)),
                ('salt', models.BinaryField(max_length=32)),
                ('tags', models.CharField(blank=True, max_length=200, null=True, verbose_name='Tags')),
                ('is_favorite', models.BooleanField(default=False)),
                ('last_accessed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cofre_credentials', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Credencial',
                'verbose_name_plural': 'Credenciais',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='PasswordAccessLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('credential_id', models.IntegerField()),
                ('action', models.CharField(choices=[('VIEW', 'view'), ('CREATE', 'create'), ('UPDATE', 'update'), ('DELETE', 'delete'), ('EXPORT', 'export')], max_length=10)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, max_length=512, null=True)),
                ('details', models.TextField(blank=True, null=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Log de acesso ao cofre',
                'verbose_name_plural': 'Logs de acesso ao cofre',
                'ordering': ['-timestamp'],
            },
        ),
    ]
