# Generated by Django 5.2.6 on 2026-07-16 22:21

import cofre_senhas.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cofre_senhas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='credential',
            name='encrypted_password',
            field=models.BinaryField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='CredentialAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(help_text='Nome do cliente/ambiente (ex.: Mercado Feller).', max_length=200, verbose_name='Identificação')),
                ('username', models.CharField(blank=True, max_length=200, null=True, verbose_name='Usuário / Login')),
                ('encrypted_password', models.BinaryField(blank=True, null=True)),
                ('encrypted_notes', models.BinaryField(blank=True, null=True)),
                ('salt', models.BinaryField(max_length=32)),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Ordem')),
                ('last_accessed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('credential', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accounts', to='cofre_senhas.credential', verbose_name='Credencial')),
            ],
            options={
                'verbose_name': 'Acesso da credencial',
                'verbose_name_plural': 'Acessos da credencial',
                'ordering': ['order', 'label'],
                'indexes': [models.Index(fields=['credential', 'order'], name='cofre_senha_credent_1b1bf7_idx')],
            },
            bases=(cofre_senhas.models._CryptoMixin, models.Model),
        ),
    ]
