# Generated by Django 5.2.6 on 2025-10-24 14:54

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CalendarEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=180)),
                ('description', models.TextField(blank=True)),
                ('start', models.DateTimeField()),
                ('end', models.DateTimeField()),
                ('all_day', models.BooleanField(default=False)),
                ('location', models.CharField(blank=True, max_length=200)),
                ('source', models.CharField(choices=[('manual', 'Manual'), ('chamado', 'Atendimentos/Chamados'), ('implantacao', 'Gestão de Implantação'), ('cs', 'CS - Satisfação')], default='manual', max_length=20)),
                ('source_object_id', models.CharField(blank=True, max_length=64)),
                ('source_label', models.CharField(blank=True, max_length=120)),
                ('color', models.CharField(default='#2563eb', max_length=9)),
                ('empresa_nome', models.CharField(blank=True, max_length=160)),
                ('icon_emoji', models.CharField(blank=True, max_length=4)),
                ('avatar_url', models.URLField(blank=True)),
                ('style_variant', models.CharField(choices=[('sticky', 'Post-it'), ('label', 'Etiqueta'), ('milestone', 'Marco'), ('progress', 'Progresso')], default='sticky', max_length=16)),
                ('progress_pct', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('is_background', models.BooleanField(default=False)),
                ('remind_minutes_before', models.PositiveSmallIntegerField(default=30, help_text='Minutos antes do início para enviar lembrete.')),
                ('reminded_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['start'],
            },
        ),
        migrations.CreateModel(
            name='EventAttendee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendee_links', to='calendario_agenda.calendarevent')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calendar_links', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Participante de Evento',
                'verbose_name_plural': 'Participantes de Evento',
                'unique_together': {('event', 'user')},
            },
        ),
        migrations.AddField(
            model_name='calendarevent',
            name='attendees',
            field=models.ManyToManyField(blank=True, related_name='events_invited', through='calendario_agenda.EventAttendee', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='EventConfirmation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('status', models.CharField(choices=[('pending', 'Pendente'), ('confirmed', 'Confirmado'), ('declined', 'Recusado')], default='pending', max_length=10)),
                ('responded_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='confirmations', to='calendario_agenda.calendarevent')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_confirmations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ReminderLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel', models.CharField(choices=[('email', 'E-mail'), ('whatsapp', 'WhatsApp')], default='email', max_length=16)),
                ('kind', models.CharField(choices=[('reminder', 'Lembrete'), ('confirmation', 'Confirmação')], default='reminder', max_length=16)),
                ('scheduled_for', models.DateTimeField(blank=True, null=True)),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reminder_logs', to='calendario_agenda.calendarevent')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_reminders', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddIndex(
            model_name='calendarevent',
            index=models.Index(fields=['start'], name='calendario__start_b57b2a_idx'),
        ),
        migrations.AddIndex(
            model_name='calendarevent',
            index=models.Index(fields=['end'], name='calendario__end_41a5b9_idx'),
        ),
        migrations.AddIndex(
            model_name='calendarevent',
            index=models.Index(fields=['source'], name='calendario__source_27a9ca_idx'),
        ),
        migrations.AddIndex(
            model_name='eventconfirmation',
            index=models.Index(fields=['status'], name='calendario__status_26a6eb_idx'),
        ),
        migrations.AddIndex(
            model_name='eventconfirmation',
            index=models.Index(fields=['created_at'], name='calendario__created_9857bb_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='eventconfirmation',
            unique_together={('event', 'user')},
        ),
        migrations.AlterUniqueTogether(
            name='reminderlog',
            unique_together={('event', 'user', 'channel', 'kind')},
        ),
    ]
