# Generated by Django 5.2.6 on 2025-10-29 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendario_agenda', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='calendarevent',
            name='contato_whatsapp',
            field=models.CharField(blank=True, help_text='Formato: 55DDDNUMERO (apenas dígitos; aceita espaços/+, será normalizado)', max_length=20, null=True, verbose_name='Contato WhatsApp'),
        ),
    ]
