# Generated by Django 5.2.6 on 2026-02-24 19:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendario_agenda', '0002_calendarevent_contato_whatsapp'),
        ('clientes_sistemas', '0007_cliente_status_financeiro_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='calendarevent',
            name='cliente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='eventos_agenda', to='clientes_sistemas.cliente', verbose_name='Cliente Vinculado'),
        ),
        migrations.AlterField(
            model_name='calendarevent',
            name='empresa_nome',
            field=models.CharField(blank=True, max_length=160, verbose_name='Empresa (Texto Livre)'),
        ),
    ]
