# Generated by Django 5.2.6 on 2026-07-17 00:30

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_conhecimento', '0003_auto_20250926_1701'),
        ('sistemas', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='artigo',
            options={'ordering': ['-atualizado_em']},
        ),
        migrations.AddField(
            model_name='artigo',
            name='tipo',
            field=models.CharField(choices=[('procedimento', 'Procedimento'), ('erro', 'Erro / Troubleshooting'), ('tutorial', 'Tutorial'), ('faq', 'FAQ')], default='procedimento', max_length=20),
        ),
        migrations.AlterField(
            model_name='artigo',
            name='codigo',
            field=models.CharField(db_index=True, editable=False, max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='artigo',
            name='hashtags',
            field=models.CharField(blank=True, help_text='Separe as hashtags por vírgula. Ex: instalação, erro, sql', max_length=255),
        ),
        migrations.AddIndex(
            model_name='artigo',
            index=models.Index(fields=['sistema', '-atualizado_em'], name='base_conhec_sistema_125b0d_idx'),
        ),
    ]
