# Generated by Django 5.2.6 on 2026-07-18 13:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_conhecimento', '0004_alter_artigo_options_artigo_tipo_alter_artigo_codigo_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='artigo',
            name='visualizacoes',
            field=models.PositiveIntegerField(default=0, editable=False),
        ),
        migrations.CreateModel(
            name='ArtigoAcesso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visto_em', models.DateTimeField(auto_now=True)),
                ('vezes', models.PositiveIntegerField(default=1)),
                ('artigo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='acessos', to='base_conhecimento.artigo')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='artigos_acessados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Acesso a artigo',
                'verbose_name_plural': 'Acessos a artigos',
                'ordering': ['-visto_em'],
                'indexes': [models.Index(fields=['usuario', '-visto_em'], name='base_conhec_usuario_a3eaf2_idx')],
                'constraints': [models.UniqueConstraint(fields=('usuario', 'artigo'), name='unique_acesso_usuario_artigo')],
            },
        ),
    ]
