# Generated by Django 5.2.6 on 2026-07-21 23:15

import pgvector.django.vector
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_conhecimento', '0005_artigo_visualizacoes_artigoacesso'),
    ]

    operations = [
        migrations.AddField(
            model_name='artigo',
            name='embedding',
            field=pgvector.django.vector.VectorField(blank=True, dimensions=768, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='artigo',
            name='embedding_atualizado_em',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
    ]
