# Generated by Django 5.2.6 on 2026-02-13 19:30

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientes_sistemas', '0004_alter_cliente_faturamento_cliente_and_more'),
        ('sistemas', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Implantacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255)),
                ('descricao', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('PLANEJAMENTO', 'Planejamento'), ('EM_ANDAMENTO', 'Em andamento'), ('AGUARDANDO_CLIENTE', 'Aguardando cliente'), ('CONCLUIDA', 'Concluída'), ('CANCELADA', 'Cancelada')], default='PLANEJAMENTO', max_length=25)),
                ('data_inicio', models.DateTimeField(default=django.utils.timezone.now)),
                ('data_prevista', models.DateTimeField(blank=True, null=True)),
                ('data_conclusao', models.DateTimeField(blank=True, null=True)),
                ('gerar_cs_automatico', models.BooleanField(default=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='implantacoes', to='clientes_sistemas.cliente')),
                ('responsavel', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='implantacoes_responsavel', to=settings.AUTH_USER_MODEL)),
                ('sistema', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='implantacoes', to='sistemas.sistema')),
            ],
        ),
    ]
