# Generated by Django 5.2.6 on 2026-04-25 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ComunicadoInterno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('NOVIDADE', 'Novidade / Atualização'), ('MANUTENCAO', 'Manutenção Programada'), ('ALERTA', 'Aviso Importante')], default='NOVIDADE', max_length=20)),
                ('titulo', models.CharField(max_length=150)),
                ('texto', models.TextField()),
                ('ativo', models.BooleanField(default=True, help_text='Desmarque para esconder da tela inicial do Lógica.Desk')),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Comunicado Interno',
                'verbose_name_plural': 'Comunicados Internos',
                'ordering': ['-data_criacao'],
            },
        ),
    ]
