# Generated by Django 5.2.6 on 2026-02-13 19:30

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientes_sistemas', '0004_alter_cliente_faturamento_cliente_and_more'),
        ('implantacao', '0001_initial'),
        ('sistemas', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Atendimento',
            fields=[
                ('numero', models.AutoField(primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=255)),
                ('descricao', models.TextField()),
                ('tipo_atendimento', models.CharField(choices=[('SUPORTE', 'Suporte'), ('ERRO', 'Erro'), ('MELHORIA', 'Melhoria'), ('IMPLANTACAO', 'Implantação'), ('TREINAMENTO', 'Treinamento'), ('CONSULTORIA', 'Consultoria')], max_length=20)),
                ('modalidade', models.CharField(choices=[('REMOTO', 'Remoto'), ('PRESENCIAL', 'Presencial'), ('HIBRIDO', 'Híbrido')], default='REMOTO', max_length=15)),
                ('prioridade', models.CharField(choices=[('BAIXA', 'Baixa'), ('MEDIA', 'Média'), ('ALTA', 'Alta'), ('CRITICA', 'Crítica')], default='MEDIA', max_length=10)),
                ('status', models.CharField(choices=[('ABERTO', 'Aberto'), ('EM_ANALISE', 'Em análise'), ('EM_ATENDIMENTO', 'Em atendimento'), ('AGUARDANDO_CLIENTE', 'Aguardando cliente'), ('AGUARDANDO_INTERNO', 'Aguardando interno'), ('RESOLVIDO', 'Resolvido'), ('CONCLUIDO', 'Concluído'), ('CANCELADO', 'Cancelado')], default='ABERTO', max_length=25)),
                ('data_abertura', models.DateTimeField(default=django.utils.timezone.now)),
                ('data_assumido', models.DateTimeField(blank=True, null=True)),
                ('data_conclusao', models.DateTimeField(blank=True, null=True)),
                ('sla_horas', models.PositiveIntegerField(default=24)),
                ('resolvido_no_prazo', models.BooleanField(default=False)),
                ('reaberto', models.BooleanField(default=False)),
                ('enviar_para_cs', models.BooleanField(default=False)),
                ('cs_gerado', models.BooleanField(default=False)),
                ('pontos_gerados', models.IntegerField(default=0)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='atendimentos', to='clientes_sistemas.cliente')),
                ('implantacao_relacionada', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='atendimentos_vinculados', to='implantacao.implantacao')),
                ('sistema', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='atendimentos', to='sistemas.sistema')),
                ('tecnico_responsavel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='atendimentos_responsavel', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AtendimentoHistorico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_anterior', models.CharField(blank=True, choices=[('ABERTO', 'Aberto'), ('EM_ANALISE', 'Em análise'), ('EM_ATENDIMENTO', 'Em atendimento'), ('AGUARDANDO_CLIENTE', 'Aguardando cliente'), ('AGUARDANDO_INTERNO', 'Aguardando interno'), ('RESOLVIDO', 'Resolvido'), ('CONCLUIDO', 'Concluído'), ('CANCELADO', 'Cancelado')], max_length=25, null=True)),
                ('status_novo', models.CharField(choices=[('ABERTO', 'Aberto'), ('EM_ANALISE', 'Em análise'), ('EM_ATENDIMENTO', 'Em atendimento'), ('AGUARDANDO_CLIENTE', 'Aguardando cliente'), ('AGUARDANDO_INTERNO', 'Aguardando interno'), ('RESOLVIDO', 'Resolvido'), ('CONCLUIDO', 'Concluído'), ('CANCELADO', 'Cancelado')], max_length=25)),
                ('comentario', models.TextField(blank=True, null=True)),
                ('data', models.DateTimeField(default=django.utils.timezone.now)),
                ('atendimento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historico', to='atendimentos_chamados.atendimento')),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
