# Generated by Django 5.2.6 on 2026-02-13 20:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atendimentos_chamados', '0001_initial'),
        ('clientes_sistemas', '0004_alter_cliente_faturamento_cliente_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Setor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('ativo', models.BooleanField(default=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='atendimento',
            name='cs_gerado',
        ),
        migrations.RemoveField(
            model_name='atendimento',
            name='data_assumido',
        ),
        migrations.RemoveField(
            model_name='atendimento',
            name='enviar_para_cs',
        ),
        migrations.RemoveField(
            model_name='atendimento',
            name='implantacao_relacionada',
        ),
        migrations.RemoveField(
            model_name='atendimento',
            name='modalidade',
        ),
        migrations.RemoveField(
            model_name='atendimento',
            name='pontos_gerados',
        ),
        migrations.RemoveField(
            model_name='atendimento',
            name='reaberto',
        ),
        migrations.RemoveField(
            model_name='atendimento',
            name='sistema',
        ),
        migrations.RemoveField(
            model_name='atendimento',
            name='tipo_atendimento',
        ),
        migrations.RemoveField(
            model_name='atendimentohistorico',
            name='status_anterior',
        ),
        migrations.RemoveField(
            model_name='atendimentohistorico',
            name='status_novo',
        ),
        migrations.AlterField(
            model_name='atendimento',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clientes_sistemas.cliente'),
        ),
        migrations.AlterField(
            model_name='atendimento',
            name='prioridade',
            field=models.CharField(choices=[('BAIXA', 'Baixa'), ('MEDIA', 'Média'), ('ALTA', 'Alta'), ('CRITICA', 'Crítica')], max_length=10),
        ),
        migrations.AlterField(
            model_name='atendimento',
            name='sla_horas',
            field=models.IntegerField(default=24),
        ),
        migrations.AlterField(
            model_name='atendimento',
            name='status',
            field=models.CharField(choices=[('ABERTO', 'Aberto'), ('EM_ATENDIMENTO', 'Em Atendimento'), ('AGUARDANDO_CLIENTE', 'Aguardando Cliente'), ('CONCLUIDO', 'Concluído')], default='ABERTO', max_length=25),
        ),
        migrations.AlterField(
            model_name='atendimento',
            name='tecnico_responsavel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='atendimentohistorico',
            name='data',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AddField(
            model_name='atendimento',
            name='setor_atual',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='atendimentos', to='atendimentos_chamados.setor'),
        ),
        migrations.AddField(
            model_name='atendimentohistorico',
            name='setor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='atendimentos_chamados.setor'),
        ),
    ]
