# Generated by Django 5.2.6 on 2026-02-20 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atendimentos_chamados', '0002_setor_remove_atendimento_cs_gerado_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='atendimento',
            name='abrir_cs_pos_atendimento',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='atendimento',
            name='implantacao_cliente_novo',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='atendimento',
            name='implantacao_modulo_novo',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='atendimento',
            name='numero_os',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='atendimento',
            name='possui_treinamento',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='atendimento',
            name='tipo_treinamento',
            field=models.CharField(blank=True, choices=[('ONLINE', 'Online'), ('PRESENCIAL', 'Presencial')], max_length=15, null=True),
        ),
    ]
