# Generated by Django 5.2.6 on 2026-04-23 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atendimentos_chamados', '0003_atendimento_abrir_cs_pos_atendimento_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='atendimento',
            name='status',
            field=models.CharField(choices=[('ABERTO', 'Aberto'), ('EM_ATENDIMENTO', 'Em Atendimento'), ('AGUARDANDO_CLIENTE', 'Aguardando Cliente'), ('AGUARDANDO_DESENVOLVIMENTO', 'Aguardando Desenv.'), ('CONCLUIDO', 'Concluído')], default='ABERTO', max_length=30),
        ),
    ]
