# Generated by Django 5.2.6 on 2026-06-18 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atendimentos_chamados', '0004_alter_atendimento_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='atendimento',
            name='flag_backup',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='atendimento',
            name='flag_conversao_dados',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='atendimento',
            name='flag_instalacao_equip',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='atendimento',
            name='flag_mobilidade',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='atendimento',
            name='flag_tef_incluso',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='atendimento',
            name='trein_boletos',
            field=models.BooleanField(default=False, verbose_name='Emissão de Boletos'),
        ),
        migrations.AddField(
            model_name='atendimento',
            name='trein_cadastros',
            field=models.BooleanField(default=False, verbose_name='Cadastros e Estoque'),
        ),
        migrations.AddField(
            model_name='atendimento',
            name='trein_entrada_nf',
            field=models.BooleanField(default=False, verbose_name='Entrada de NF'),
        ),
        migrations.AddField(
            model_name='atendimento',
            name='trein_estoque',
            field=models.BooleanField(default=False, verbose_name='Controle de Estoque'),
        ),
        migrations.AddField(
            model_name='atendimento',
            name='trein_financeiro',
            field=models.BooleanField(default=False, verbose_name='Módulo Financeiro'),
        ),
        migrations.AddField(
            model_name='atendimento',
            name='trein_nfce',
            field=models.BooleanField(default=False, verbose_name='Cupom NFC-e'),
        ),
        migrations.AddField(
            model_name='atendimento',
            name='trein_saida_nf',
            field=models.BooleanField(default=False, verbose_name='Saída de NF'),
        ),
        migrations.AddField(
            model_name='atendimento',
            name='whatsapp_contato',
            field=models.CharField(blank=True, help_text='WhatsApp de quem vai acompanhar a implantação', max_length=50, null=True),
        ),
    ]
