# Generated by Django 5.2.6 on 2026-06-18 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atendimentos_chamados', '0005_atendimento_flag_backup_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='atendimento',
            name='flag_data_center',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='atendimento',
            name='trein_os_service',
            field=models.BooleanField(default=False, verbose_name='OS-Service'),
        ),
    ]
