# Generated by Django 5.2.6 on 2026-03-16 18:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whatsapp_bot', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TagAtendimento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('cor', models.CharField(default='#6366f1', max_length=7)),
            ],
        ),
        migrations.AddField(
            model_name='chatsession',
            name='setor_atual',
            field=models.CharField(choices=[('SUPORTE', 'Suporte'), ('FINANCEIRO', 'Financeiro'), ('COMERCIAL', 'Comercial'), ('TECNICO', 'Assistência Técnica')], default='SUPORTE', max_length=20),
        ),
        migrations.AddField(
            model_name='message',
            name='tecnico',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='message',
            name='sender_type',
            field=models.CharField(choices=[('CLIENTE', 'Cliente'), ('IA', 'IA'), ('TECNICO', 'Técnico'), ('SISTEMA', 'Sistema'), ('INTERNO', 'Comentário Interno')], max_length=10),
        ),
        migrations.AddField(
            model_name='chatsession',
            name='tags',
            field=models.ManyToManyField(blank=True, to='whatsapp_bot.tagatendimento'),
        ),
    ]
