# Generated by Django 5.2.6 on 2026-03-16 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whatsapp_bot', '0002_tagatendimento_chatsession_setor_atual_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatsession',
            name='profile_pic',
            field=models.URLField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='chatsession',
            name='push_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='chatsession',
            name='whatsapp_number',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
