# Generated by Django 5.2.6 on 2026-03-17 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whatsapp_bot', '0003_chatsession_profile_pic_chatsession_push_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='media_url',
            field=models.URLField(blank=True, max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='chatsession',
            name='setor_atual',
            field=models.CharField(choices=[('SUPORTE', 'Suporte Técnico'), ('FINANCEIRO', 'Financeiro'), ('COMERCIAL', 'Comercial / Vendas'), ('ASSISTENCIA', 'Assistência Técnica')], default='SUPORTE', max_length=20),
        ),
    ]
