# Generated by Django 5.2.6 on 2026-03-17 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whatsapp_bot', '0004_message_media_url_alter_chatsession_setor_atual'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatsession',
            name='mensagens_nao_lidas',
            field=models.IntegerField(default=0),
        ),
    ]
