# Generated by Django 5.2.6 on 2026-03-17 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whatsapp_bot', '0005_chatsession_mensagens_nao_lidas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='media_url',
            field=models.TextField(blank=True, null=True),
        ),
    ]
