# Generated by Django 5.2.6 on 2026-03-19 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whatsapp_bot', '0007_message_is_deleted_message_is_edited_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MensagemRapida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(help_text='Ex: Saudação Bom Dia', max_length=100)),
                ('atalho', models.CharField(help_text='Ex: /bomdia', max_length=30, unique=True)),
                ('texto', models.TextField(help_text='Use {nome} para inserir o nome do atendente automaticamente na mensagem.')),
            ],
            options={
                'ordering': ['atalho'],
            },
        ),
    ]
