# Generated by Django 5.2.6 on 2026-03-19 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whatsapp_bot', '0008_mensagemrapida'),
    ]

    operations = [
        migrations.CreateModel(
            name='BotConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chave_api_gemini', models.CharField(max_length=255)),
                ('mensagem_saudacao', models.TextField(default='Olá! Sou o assistente virtual da Lógica Mais. Como posso te ajudar?')),
                ('prompt_ia_triagem', models.TextField(default='Você é um assistente de triagem da empresa Lógica Mais. Classifique o pedido do cliente nos seguintes setores: SUPORTE (Sistemas), ASSISTENCIA (Equipamentos), COMERCIAL ou FINANCEIRO.')),
            ],
            options={
                'verbose_name': 'Configuração do Bot',
            },
        ),
        migrations.AddField(
            model_name='chatsession',
            name='nota_nps',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='chatsession',
            name='nota_tecnico',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='chatsession',
            name='status',
            field=models.CharField(choices=[('TRIAGEM', 'Em Triagem pela IA'), ('PENDENTE', 'Aguardando Técnico'), ('EM_ATENDIMENTO', 'Em Atendimento Humano'), ('AVALIACAO_TECNICO', 'Aguardando Nota do Técnico (1-5)'), ('AVALIACAO_NPS', 'Aguardando Nota da Empresa (0-10)'), ('FINALIZADO', 'Atendimento Encerrado')], default='TRIAGEM', max_length=20),
        ),
        migrations.AlterField(
            model_name='chatsession',
            name='setor_atual',
            field=models.CharField(choices=[('TRIAGEM', 'Triagem'), ('SUPORTE', 'Suporte Sistemas'), ('FINANCEIRO', 'Financeiro'), ('COMERCIAL', 'Comercial / Vendas'), ('ASSISTENCIA', 'Assistência Técnica')], default='TRIAGEM', max_length=20),
        ),
    ]
