# Generated by Django 5.2.6 on 2026-03-20 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whatsapp_bot', '0009_botconfig_chatsession_nota_nps_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='botconfig',
            name='horario_fim_sabado',
            field=models.TimeField(default='17:30'),
        ),
        migrations.AddField(
            model_name='botconfig',
            name='horario_fim_semana',
            field=models.TimeField(default='20:00'),
        ),
        migrations.AddField(
            model_name='botconfig',
            name='horario_inicio_sabado',
            field=models.TimeField(default='07:30'),
        ),
        migrations.AddField(
            model_name='botconfig',
            name='horario_inicio_semana',
            field=models.TimeField(default='07:30'),
        ),
        migrations.AddField(
            model_name='botconfig',
            name='instrucoes_suporte_24h',
            field=models.TextField(blank=True, help_text='Cole aqui as soluções dos problemas mais comuns, senhas de reset, links, etc.', null=True),
        ),
        migrations.AddField(
            model_name='botconfig',
            name='mensagem_fora_horario',
            field=models.TextField(default='Nossos técnicos estão descansando agora, mas eu sou o Analista Digital da Lógica Mais! Posso tentar analisar seu erro e resolvermos juntos agora mesmo, o que acha?'),
        ),
        migrations.AddField(
            model_name='botconfig',
            name='prompt_analista_digital',
            field=models.TextField(default='Você é um Analista de Sistemas da Lógica Mais. Seja técnico, resolva problemas baseando-se nas instruções fornecidas.'),
        ),
        migrations.AddField(
            model_name='chatsession',
            name='tentativas_ia',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='botconfig',
            name='mensagem_saudacao',
            field=models.TextField(default='Olá! Sou a assistente virtual da Lógica Mais. Como posso te ajudar?'),
        ),
        migrations.AlterField(
            model_name='botconfig',
            name='prompt_ia_triagem',
            field=models.TextField(default='Você é a recepcionista da Lógica Mais. Classifique o pedido do cliente nos setores: SUPORTE, ASSISTENCIA, COMERCIAL ou FINANCEIRO. Responda APENAS com o nome do setor.'),
        ),
        migrations.AlterField(
            model_name='chatsession',
            name='status',
            field=models.CharField(choices=[('TRIAGEM', 'Em Triagem pela IA (Recepção)'), ('SUPORTE_IA', 'Em Atendimento pela IA (Analista Digital)'), ('PENDENTE', 'Aguardando Técnico Humano'), ('EM_ATENDIMENTO', 'Em Atendimento Humano'), ('AVALIACAO_TECNICO', 'Aguardando Nota do Técnico (1-5)'), ('AVALIACAO_NPS', 'Aguardando Nota da Empresa (0-10)'), ('FINALIZADO', 'Atendimento Encerrado')], default='TRIAGEM', max_length=20),
        ),
    ]
