# Generated by Django 5.2.6 on 2026-03-20 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whatsapp_bot', '0010_botconfig_horario_fim_sabado_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatsession',
            name='whatsapp_number',
            field=models.CharField(max_length=100),
        ),
    ]
