# Generated by Django 5.2.6 on 2026-03-28 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whatsapp_bot', '0011_alter_chatsession_whatsapp_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='ack',
            field=models.IntegerField(default=0, help_text='0=Pendente, 1=Enviado, 2=Entregue, 3=Lido, 4=Tocado'),
        ),
    ]
