# Generated by Django 5.2.6 on 2026-07-22 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whatsapp_bot', '0012_message_ack'),
    ]

    operations = [
        migrations.AddField(
            model_name='botconfig',
            name='modelo_ia',
            field=models.CharField(default='gemini-flash-latest', help_text='Modelo Gemini usado pela IA (ex: gemini-flash-latest, gemini-3.5-flash, gemini-2.5-flash). Troque aqui pra testar outro modelo sem mexer no código.', max_length=100),
        ),
    ]
