# Generated by Django 5.2.6 on 2026-07-22 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whatsapp_bot', '0013_botconfig_modelo_ia'),
    ]

    operations = [
        migrations.AddField(
            model_name='botconfig',
            name='identidade_empresa',
            field=models.TextField(blank=True, help_text='Quem somos, o que vendemos. Vai no prompt da IA. Deixe vazio para usar o padrão do sistema.', null=True, verbose_name='Identidade da Empresa'),
        ),
        migrations.AddField(
            model_name='botconfig',
            name='modelo_tts',
            field=models.CharField(blank=True, default='gemini-2.5-flash-preview-tts', help_text='Ex: gemini-2.5-flash-preview-tts ou gemini-3.1-flash-tts-preview', max_length=100, verbose_name='Modelo de Voz (TTS)'),
        ),
        migrations.AddField(
            model_name='botconfig',
            name='regras_negocio',
            field=models.TextField(blank=True, help_text='Regras específicas (links de boleto, políticas...). Uma por linha. Deixe vazio para usar o padrão.', null=True, verbose_name='Regras de Negócio'),
        ),
        migrations.AddField(
            model_name='botconfig',
            name='voz_tts',
            field=models.CharField(blank=True, default='Vindemiatrix', help_text='Nome da voz do Gemini. Veja a lista de opções no guia.', max_length=50, verbose_name='Voz da IA'),
        ),
    ]
