# Generated by Django 5.2.6 on 2025-10-17 18:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sistemas', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfigHoras',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('horas_dia', models.DecimalField(decimal_places=2, default=8.0, max_digits=4, verbose_name='Horas por dia')),
                ('pausa_almoco_min', models.PositiveIntegerField(default=60, verbose_name='Pausa almoço (min)')),
                ('considerar_sabado', models.BooleanField(default=False)),
                ('considerar_domingo', models.BooleanField(default=False)),
                ('ativo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Configuração de Horas',
                'verbose_name_plural': 'Configurações de Horas',
            },
        ),
        migrations.CreateModel(
            name='Apontamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('hora_inicio', models.TimeField()),
                ('hora_fim', models.TimeField()),
                ('tipo', models.CharField(choices=[('normal', 'Normal'), ('plantao', 'Plantão'), ('desloc', 'Deslocamento'), ('intervalo', 'Intervalo/Almoço'), ('outro', 'Outro')], default='normal', max_length=10)),
                ('descricao', models.TextField(blank=True)),
                ('minutos_total', models.PositiveIntegerField(default=0, editable=False)),
                ('minutos_extra', models.PositiveIntegerField(default=0, editable=False)),
                ('status', models.CharField(choices=[('rascunho', 'Rascunho'), ('pendente', 'Pendente Aprovação'), ('aprovado', 'Aprovado'), ('reprovado', 'Reprovado')], default='rascunho', max_length=12)),
                ('aprovado_em', models.DateTimeField(blank=True, null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('aprovado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='aprovacoes_apontamentos', to=settings.AUTH_USER_MODEL)),
                ('sistema', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sistemas.sistema')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='apontamentos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Apontamento',
                'verbose_name_plural': 'Apontamentos',
                'ordering': ['-data', '-hora_inicio'],
                'indexes': [models.Index(fields=['usuario', 'data', 'status'], name='controle_ho_usuario_0bfb58_idx')],
            },
        ),
        migrations.CreateModel(
            name='FechamentoMensal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('competencia', models.DateField(help_text='Use o primeiro dia do mês (YYYY-MM-01)')),
                ('minutos_trabalhados', models.PositiveIntegerField(default=0)),
                ('minutos_extras', models.PositiveIntegerField(default=0)),
                ('saldo_banco', models.IntegerField(default=0, help_text='Saldo acumulado (minutos), pode ser negativo.')),
                ('status', models.CharField(choices=[('aberto', 'Aberto'), ('fechado', 'Fechado')], default='aberto', max_length=10)),
                ('fechado_em', models.DateTimeField(blank=True, null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('fechado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fechamentos_fechados', to=settings.AUTH_USER_MODEL)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fechamentos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Fechamento Mensal',
                'verbose_name_plural': 'Fechamentos Mensais',
                'unique_together': {('usuario', 'competencia')},
            },
        ),
    ]
