# Generated by Django 5.2.6 on 2025-10-17 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controle_horas', '0002_apontamento_novos_campos'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='apontamento',
            options={'ordering': ['-data', 'usuario']},
        ),
        migrations.RemoveField(
            model_name='apontamento',
            name='hora_fim',
        ),
        migrations.RemoveField(
            model_name='apontamento',
            name='hora_inicio',
        ),
        migrations.RemoveField(
            model_name='apontamento',
            name='minutos_extra',
        ),
        migrations.RemoveField(
            model_name='apontamento',
            name='minutos_total',
        ),
        migrations.RemoveField(
            model_name='confighoras',
            name='pausa_almoco_min',
        ),
        migrations.AlterField(
            model_name='apontamento',
            name='tipo',
            field=models.CharField(choices=[('normal', 'Normal (4 marcações)'), ('plantao', 'Plantão (2 marcações)'), ('atualizacao', 'Atualização (2 marcações)'), ('emergencia', 'Atendimento Emergência (2 marcações)'), ('implantacao', 'Implantação (2 marcações)')], default='normal', max_length=20),
        ),
        migrations.DeleteModel(
            name='FechamentoMensal',
        ),
    ]
