# Generated by Django 5.2.6 on 2025-10-23 20:55

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controle_horas', '0004_confighoras_add_pausa_almoco_min'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FechamentoMensal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('competencia', models.DateField(help_text='Use o primeiro dia do mês (ex.: 2025-10-01 para out/2025).')),
                ('fechado', models.BooleanField(default=False)),
                ('fechado_em', models.DateTimeField(blank=True, null=True)),
                ('observacao', models.TextField(blank=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Fechamento Mensal',
                'verbose_name_plural': 'Fechamentos Mensais',
            },
        ),
        migrations.AlterModelOptions(
            name='apontamento',
            options={'ordering': ('-data', '-atualizado_em')},
        ),
        migrations.RemoveIndex(
            model_name='apontamento',
            name='controle_ho_usuario_0bfb58_idx',
        ),
        migrations.RemoveField(
            model_name='apontamento',
            name='sistema',
        ),
        migrations.AlterField(
            model_name='apontamento',
            name='aprovado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='aprovacoes_controle_horas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='apontamento',
            name='descricao',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='apontamento',
            name='status',
            field=models.CharField(choices=[('rascunho', 'Rascunho'), ('pendente', 'Pendente'), ('aprovado', 'Aprovado'), ('reprovado', 'Reprovado')], default='rascunho', max_length=20),
        ),
        migrations.AlterField(
            model_name='apontamento',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='confighoras',
            name='horas_dia',
            field=models.DecimalField(decimal_places=2, default=Decimal('8.00'), help_text='Carga diária em horas decimais (ex.: 8.00, 8.80).', max_digits=4),
        ),
        migrations.AddIndex(
            model_name='apontamento',
            index=models.Index(fields=['usuario', 'data'], name='controle_ho_usuario_e0d284_idx'),
        ),
        migrations.AddIndex(
            model_name='apontamento',
            index=models.Index(fields=['status', 'data'], name='controle_ho_status_9f5321_idx'),
        ),
        migrations.AddField(
            model_name='fechamentomensal',
            name='fechado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fechamentos_realizados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='fechamentomensal',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fechamentos_mensais', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='fechamentomensal',
            constraint=models.UniqueConstraint(fields=('usuario', 'competencia'), name='unique_fechamento_usuario_competencia'),
        ),
    ]
