# Generated by Django 5.2.6 on 2026-06-18 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controle_horas', '0006_agendaevento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agendaevento',
            name='tipo',
            field=models.CharField(choices=[('plantao', 'Plantão'), ('home_office', 'Home Office'), ('ferias', 'Férias'), ('folga_compensada', 'Folga Compensada')], max_length=20),
        ),
    ]
