# Generated by Django 5.2.6 on 2026-08-20 21:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes_sistemas', '0010_cliente_data_consulta_cnpj'),
        ('controle_horas', '0007_alter_agendaevento_tipo'),
    ]

    operations = [
        migrations.AddField(
            model_name='apontamento',
            name='cliente_atualizacao',
            field=models.ForeignKey(blank=True, help_text="Preenchido quando tipo='atualizacao': qual cliente foi atualizado.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='apontamentos_atualizacao', to='clientes_sistemas.cliente', verbose_name='Cliente (Atualização)'),
        ),
    ]
