# Generated by Django 5.2.6 on 2026-02-20 19:16

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientes_sistemas', '0005_cliente_serial_sistema'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EventoCS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_contato', models.CharField(choices=[('FOLLOWUP', 'Follow-up'), ('POS_IMPLANTACAO', 'Pós-Implantação'), ('TREINAMENTO', 'Treinamento'), ('RENOVACAO', 'Renovação'), ('RISCO', 'Cliente em Risco'), ('OPORTUNIDADE', 'Oportunidade de Venda')], default='FOLLOWUP', max_length=20)),
                ('status', models.CharField(choices=[('PENDENTE', 'Pendente'), ('REALIZADO', 'Realizado'), ('CANCELADO', 'Cancelado')], default='PENDENTE', max_length=15)),
                ('nivel_risco', models.CharField(choices=[('BAIXO', 'Baixo'), ('MEDIO', 'Médio'), ('ALTO', 'Alto'), ('CRITICO', 'Crítico')], default='BAIXO', max_length=10)),
                ('health_score', models.IntegerField(default=100)),
                ('gera_oportunidade', models.BooleanField(default=False)),
                ('data_prevista', models.DateField(default=django.utils.timezone.now)),
                ('data_realizada', models.DateField(blank=True, null=True)),
                ('observacoes', models.TextField(blank=True, null=True)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eventos_cs', to='clientes_sistemas.cliente')),
                ('responsavel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
