# Generated by Django 5.2.6 on 2026-03-16 16:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atendimentos_chamados', '0003_atendimento_abrir_cs_pos_atendimento_and_more'),
        ('cs_satisfacao', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventocs',
            name='origem_atendimento',
            field=models.ForeignKey(blank=True, help_text='Chamado que originou este CS automaticamente', null=True, on_delete=django.db.models.deletion.SET_NULL, to='atendimentos_chamados.atendimento'),
        ),
    ]
