# Generated by Django 5.2.6 on 2026-04-06 16:43

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes_sistemas', '0008_cliente_observacoes'),
        ('cs_satisfacao', '0002_eventocs_origem_atendimento'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CancelamentoCliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_cancelamento', models.DateField(default=django.utils.timezone.now, help_text='Data em que o cliente encerrou o contrato')),
                ('motivo', models.TextField(help_text='Motivo detalhado do cancelamento (Ex: Preço, Concorrente, Fechou a empresa, etc.)')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cancelamentos', to='clientes_sistemas.cliente')),
                ('registrado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
