# Generated by Django 5.2.6 on 2026-04-23 14:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atendimentos_chamados', '0003_atendimento_abrir_cs_pos_atendimento_and_more'),
        ('cs_satisfacao', '0003_cancelamentocliente'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventocs',
            name='health_score',
        ),
        migrations.RemoveField(
            model_name='eventocs',
            name='nivel_risco',
        ),
        migrations.AddField(
            model_name='eventocs',
            name='motivo_risco',
            field=models.CharField(choices=[('NENHUM', 'Nenhum / Não se aplica'), ('ATENDIMENTO', 'Reclamação do Atendimento/Comercial'), ('FUNCIONALIDADE', 'Falta de Funcionalidade'), ('BUGS', 'Bugs ou Problemas não resolvidos'), ('CONCORRENCIA', 'Ameaça da Concorrência (Preço/Sistema)'), ('FINANCEIRO', 'Dificuldade Financeira do Cliente')], default='NENHUM', max_length=20),
        ),
        migrations.AlterField(
            model_name='eventocs',
            name='origem_atendimento',
            field=models.ForeignKey(blank=True, help_text='Chamado que originou este alerta de CS', null=True, on_delete=django.db.models.deletion.SET_NULL, to='atendimentos_chamados.atendimento'),
        ),
        migrations.AlterField(
            model_name='eventocs',
            name='tipo_contato',
            field=models.CharField(choices=[('ONBOARDING', 'Pós-Implantação (Onboarding)'), ('FOLLOWUP', 'Acompanhamento de Rotina'), ('TREINAMENTO', 'Treinamento Técnico'), ('RENOVACAO', 'Renovação de Contrato'), ('ALERTA', 'Alerta de Risco / Insatisfação'), ('RETENCAO', 'Ação de Retenção / Negociação'), ('OPORTUNIDADE', 'Oportunidade de Venda (Upsell)')], default='FOLLOWUP', max_length=20),
        ),
    ]
