# Generated by Django 5.2.6 on 2026-07-20 03:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemColecionavel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('descricao', models.CharField(blank=True, max_length=200)),
                ('icone', models.CharField(default='fa-puzzle-piece', max_length=40)),
                ('raridade', models.CharField(choices=[('COMUM', 'Comum'), ('RARO', 'Raro'), ('EPICO', 'Épico'), ('LENDARIO', 'Lendário')], default='COMUM', max_length=10)),
                ('total_pecas', models.IntegerField(default=4, help_text='Quantas peças formam o item')),
                ('po_ao_desencantar', models.IntegerField(default=8, help_text='Pó ganho ao desencantar 1 peça deste item')),
                ('po_para_craftar', models.IntegerField(default=28, help_text='Pó gasto para craftar 1 peça deste item')),
                ('efeito', models.CharField(choices=[('HOME_OFFICE', 'Home Office (1 dia remoto)'), ('DAY_OFF', 'Day Off (folga)'), ('PACK_XP', 'Pack de XP (turbo no perfil)'), ('FISICO', 'Item físico (entregue pela gestão)')], default='FISICO', max_length=15)),
                ('valor_efeito', models.IntegerField(default=0, help_text='Ex: quanto XP o Pack de XP concede')),
                ('ativo', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='ItemLojaOficial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('descricao', models.TextField(blank=True)),
                ('preco_lc', models.IntegerField()),
                ('icone', models.CharField(default='fa-store', max_length=40)),
                ('estoque', models.IntegerField(default=-1, help_text='-1 = ilimitado')),
                ('ativo', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='MoldeMissao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('descricao', models.CharField(blank=True, max_length=200)),
                ('tipo', models.CharField(choices=[('DIARIA', 'Diária'), ('SEMANAL', 'Semanal'), ('MENSAL', 'Mensal')], max_length=10)),
                ('gatilho', models.CharField(choices=[('fechar_chamado', 'Fechar Atendimento'), ('finalizar_chat', 'Finalizar Chat (bot)'), ('finalizar_grupo', 'Atender em Grupo'), ('responder_grupo', 'Responder em Grupo'), ('registrar_contato_cs', 'Registrar CS'), ('feedback_5_estrelas', 'Avaliação 5 estrelas'), ('cadastrar_base_conhecimento', 'Criar Artigo'), ('subir_arquivo', 'Subir Instalador'), ('criar_evento_agenda', 'Agendar no Calendário'), ('cadastrar_cliente', 'Cadastrar Cliente'), ('vincular_cliente', 'Vincular Cliente')], max_length=50)),
                ('meta_min', models.IntegerField(default=1)),
                ('meta_max', models.IntegerField(default=1)),
                ('recompensa_lc', models.IntegerField(default=0)),
                ('recompensa_xp', models.IntegerField(default=0)),
                ('peso_sorteio', models.IntegerField(default=1, help_text='Chance relativa de ser sorteada')),
                ('ativa', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='PasseColetivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ano_mes', models.CharField(help_text='AAAA-MM', max_length=7, unique=True)),
                ('titulo', models.CharField(default='Meta da Equipe', max_length=100)),
                ('pontos_atuais', models.IntegerField(default=0)),
                ('ativo', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Carteira',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('saldo_moedas', models.IntegerField(default=0, help_text='Lógica Coins (LC) disponíveis')),
                ('xp_total', models.IntegerField(default=0, help_text='XP acumulado de toda a vida')),
                ('nivel_atual', models.IntegerField(default=1)),
                ('po_magico', models.IntegerField(default=0, help_text='Pó Mágico — matéria-prima para craftar peças')),
                ('ofensiva_diaria', models.IntegerField(default=0, help_text='Dias seguidos de check-in')),
                ('maior_ofensiva', models.IntegerField(default=0, help_text='Recorde de ofensiva')),
                ('ultimo_resgate_diario', models.DateField(blank=True, null=True)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='carteira', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-xp_total',),
            },
        ),
        migrations.CreateModel(
            name='ItemInventario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_snapshot', models.CharField(help_text='Nome do item no momento', max_length=100)),
                ('status', models.CharField(choices=[('DISPONIVEL', 'Disponível'), ('A_VENDA', 'À venda no mercado'), ('RESGATADO', 'Resgatado (usado)')], default='DISPONIVEL', max_length=12)),
                ('data_obtencao', models.DateTimeField(auto_now_add=True)),
                ('item', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='recompensas.itemcolecionavel')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MissaoAtiva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('DIARIA', 'Diária'), ('SEMANAL', 'Semanal'), ('MENSAL', 'Mensal')], max_length=10)),
                ('gatilho', models.CharField(max_length=50)),
                ('titulo', models.CharField(max_length=100)),
                ('descricao', models.CharField(blank=True, max_length=200)),
                ('meta_quantidade', models.IntegerField(default=1)),
                ('recompensa_lc', models.IntegerField(default=0)),
                ('recompensa_xp', models.IntegerField(default=0)),
                ('periodo_inicio', models.DateField()),
                ('periodo_fim', models.DateField()),
                ('molde', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='instancias', to='recompensas.moldemissao')),
            ],
        ),
        migrations.CreateModel(
            name='MarcoPasse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordem', models.IntegerField(default=1)),
                ('pontos_necessarios', models.IntegerField()),
                ('recompensa_titulo', models.CharField(help_text='Ex: Cuca para a equipe', max_length=120)),
                ('recompensa_descricao', models.CharField(blank=True, max_length=200)),
                ('icone', models.CharField(default='fa-gift', max_length=40)),
                ('atingido', models.BooleanField(default=False)),
                ('data_atingido', models.DateTimeField(blank=True, null=True)),
                ('passe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='marcos', to='recompensas.passecoletivo')),
            ],
            options={
                'ordering': ('ordem',),
            },
        ),
        migrations.CreateModel(
            name='PecaInventario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_peca', models.IntegerField()),
                ('origem', models.CharField(default='roleta', max_length=20)),
                ('data', models.DateTimeField(auto_now_add=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recompensas.itemcolecionavel')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pecas', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AnuncioMercado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_conteudo', models.CharField(choices=[('ITEM', 'Item completo'), ('PECA', 'Peça')], max_length=6)),
                ('preco_lc', models.IntegerField(help_text='Preço definido pelo vendedor')),
                ('descricao_venda', models.CharField(blank=True, max_length=200)),
                ('status', models.CharField(choices=[('ATIVO', 'À venda'), ('VENDIDO', 'Vendido'), ('CANCELADO', 'Cancelado')], default='ATIVO', max_length=10)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('data_venda', models.DateTimeField(blank=True, null=True)),
                ('comprador', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='compras', to=settings.AUTH_USER_MODEL)),
                ('vendedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='anuncios', to=settings.AUTH_USER_MODEL)),
                ('item_inventario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='recompensas.iteminventario')),
                ('peca_inventario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='recompensas.pecainventario')),
            ],
            options={
                'ordering': ('-data_criacao',),
            },
        ),
        migrations.CreateModel(
            name='PecaRoleta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_peca', models.IntegerField(help_text='Qual peça do item (1..total_pecas)')),
                ('peso_sorteio', models.IntegerField(default=10, help_text='Chance relativa (maior = mais comum)')),
                ('ativo', models.BooleanField(default=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pecas_roleta', to='recompensas.itemcolecionavel')),
            ],
        ),
        migrations.CreateModel(
            name='GiroRoletaLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_giro', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('peca', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='recompensas.pecaroleta')),
            ],
        ),
        migrations.CreateModel(
            name='ProgressoMissao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('progresso_atual', models.IntegerField(default=0)),
                ('concluida', models.BooleanField(default=False)),
                ('recompensa_resgatada', models.BooleanField(default=False)),
                ('data_conclusao', models.DateTimeField(blank=True, null=True)),
                ('missao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progressos', to='recompensas.missaoativa')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progressos', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ResgateLojaOficial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('custo_pago', models.IntegerField()),
                ('data_resgate', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('PENDENTE', 'Aguardando aprovação'), ('ENTREGUE', 'Entregue'), ('CANCELADO', 'Cancelado / reembolsado')], default='PENDENTE', max_length=15)),
                ('item', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='recompensas.itemlojaoficial')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resgates_oficiais', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Transacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('GANHO', 'Ganho (+)'), ('GASTO', 'Gasto (-)')], max_length=10)),
                ('valor_moedas', models.IntegerField(default=0)),
                ('valor_xp', models.IntegerField(default=0)),
                ('descricao', models.CharField(max_length=255)),
                ('data', models.DateTimeField(auto_now_add=True)),
                ('carteira', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transacoes', to='recompensas.carteira')),
            ],
            options={
                'ordering': ('-data',),
            },
        ),
        migrations.CreateModel(
            name='ContadorAcaoMensal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acao', models.CharField(max_length=60)),
                ('ano_mes', models.CharField(help_text='Formato AAAA-MM', max_length=7)),
                ('quantidade', models.IntegerField(default=0)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contadores_acao', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['usuario', 'ano_mes'], name='recompensas_usuario_fe2358_idx')],
                'unique_together': {('usuario', 'acao', 'ano_mes')},
            },
        ),
        migrations.AddIndex(
            model_name='missaoativa',
            index=models.Index(fields=['tipo', 'periodo_inicio', 'periodo_fim'], name='recompensas_tipo_194a4d_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='progressomissao',
            unique_together={('usuario', 'missao')},
        ),
    ]
