# Generated by Django 5.2.6 on 2026-09-14 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recompensas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pecainventario',
            name='status',
            field=models.CharField(choices=[('DISPONIVEL', 'Disponível'), ('A_VENDA', 'À venda no mercado')], default='DISPONIVEL', max_length=12),
        ),
    ]
