# Generated by Django 5.2.6 on 2026-08-28 20:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UsoAssistenteIA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pergunta', models.TextField()),
                ('resposta', models.TextField(blank=True)),
                ('pagina', models.CharField(blank=True, help_text='URL ou nome da tela de onde a pergunta foi feita', max_length=255)),
                ('session_id', models.CharField(blank=True, help_text='ID da ChatSession do whatsapp_bot, quando a pergunta foi feita dentro de um atendimento', max_length=100, null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('analista', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usos_assistente_ia', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Uso do Assistente IA',
                'verbose_name_plural': 'Usos do Assistente IA',
                'ordering': ['-criado_em'],
                'indexes': [models.Index(fields=['analista', 'criado_em'], name='assistente__analist_71d912_idx')],
            },
        ),
    ]
